server:
  port: 8000

spring:
  application:
    name: imcloud-customer-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123123@peer1:8761/eureka/,http://admin:123123@peer2:8762/eureka/,http://admin:123123@peer3:8763/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      #自定义元数据  kye/value都可以随便写
      my-metadata: 自定义元数据